import type { TaxIndicator } from './codebooks';

/**
 * The УЈП outbound tax-indicator list, generated from the official page at
 * https://efakturawiki.ujp.gov.mk/danocni-indikatori (mirrored in
 * `docs/ujp/tax-indicators.txt`, captured 2026-08-29).
 *
 * GENERATED FILE — do not edit by hand. Regenerate with:
 *   node tools/gen-tax-indicators.js docs/ujp/tax-indicators.txt \
 *     src/app/core/ujp/tax-indicators.generated.ts
 *
 * `vatImpact` is not a column on that page; it is inferred from the wording
 * and cross-checked against the worked examples in
 * `docs/ujp/json-examples.pdf`. Once a company has e-УЈП access the app
 * replaces this list wholesale with a live `GET /api/v1/tax-indicators`
 * response, which carries `vatImpact` authoritatively.
 *
 * `common: true` marks the codes УЈП documents individually — the short list
 * a seller actually picks from. The rest are shown behind "сите шифри".
 */
export const UJP_TAX_INDICATORS: readonly TaxIndicator[] = [
  {
    code: 'DDV-10-13',
    categoryName: 'Промет на добра кој не е предмет на оданочување во земјата',
    note: 'Прометот не е предмет на оданочување во земјата согласно член 2 и 13 од ЗДДВ',
    vatImpact: 'OSLOBODEN',
    taxGroupCode: 'DDV-G',
    common: true,
  },
  {
    code: 'DDV-10-14',
    categoryName: 'Промет на услуги кој не е предмет на оданочување во земјата',
    note: 'Прометот не е предмет на оданочување во земјата согласно член 2 и 14 од ЗДДВ.',
    vatImpact: 'OSLOBODEN',
    taxGroupCode: 'DDV-G',
    common: true,
  },
  {
    code: 'DDV-11-A',
    categoryName: 'Промет во земјата за кој данокот го пресметува примателот на прометот по општа даночна стапка од 18% (пренесување на даночна обврска согласно член 32-а од ЗДДВ)',
    note: 'Пренесување на даночна обврска согласно член 32-а од ЗДДВ',
    vatImpact: 'PRENESEN',
    taxGroupCode: 'DDV-A',
    common: true,
  },
  {
    code: 'DDV-11-B',
    categoryName: 'Промет во земјата за кој данокот го пресметува примателот на прометот по повластена даночна стапка од 5% (пренесување на даночна обврска согласно член 32-а од ЗДДВ)',
    note: 'Пренесување на даночна обврска согласно член 32-а од ЗДДВ',
    vatImpact: 'PRENESEN',
    taxGroupCode: 'DDV-B',
    common: true,
  },
  {
    code: 'DDV-11-V',
    categoryName: 'Промет во земјата за кој данокот го пресметува примателот на прометот по повластена даночна стапка од 10% (пренесување на даночна обврска согласно член 32-а од ЗДДВ)',
    note: 'Пренесување на даночна обврска согласно член 32-а од ЗДДВ',
    vatImpact: 'PRENESEN',
    taxGroupCode: 'DDV-V',
    common: true,
  },
  {
    code: 'DDV-12-4',
    categoryName: 'Примен промет во земјата за кој данокот го пресметува примателот на прометот по општа даночна стапка (член 32 точка 4 од ЗДДВ)',
    note: 'Данок кој се должи член 32 точка 4 од ЗДДВ',
    vatImpact: 'PRENESEN',
    taxGroupCode: 'DDV-A',
    common: true,
  },
  {
    code: 'DDV-12-5',
    categoryName: 'Примен промет во земјата за кој данокот го пресметува примателот на прометот по општа даночна стапка (член 32 точка 5 од ЗДДВ)',
    note: 'Данок кој се должи член 32 точка 5 од ЗДДВ',
    vatImpact: 'PRENESEN',
    taxGroupCode: 'DDV-A',
    common: true,
  },
  {
    code: 'DDV-14-4',
    categoryName: 'Примен промет во земјата за кој данокот го пресметува примателот на прометот по повластена даночна стапка (член 32 точка 4 од ЗДДВ)',
    note: 'Данок кој се должи член 32 точка 4 од ЗДДВ',
    vatImpact: 'PRENESEN',
    taxGroupCode: 'DDV-V',
    common: true,
  },
  {
    code: 'DDV-14-5',
    categoryName: 'Примен промет во земјата за кој данокот го пресметува примателот на прометот по повластена даночна стапка (член 32 точка 5 од ЗДДВ)',
    note: 'Данок кој се должи член 32 точка 5 од ЗДДВ',
    vatImpact: 'PRENESEN',
    taxGroupCode: 'DDV-V',
    common: true,
  },
  {
    code: 'DDV-7-I',
    categoryName: 'Извоз - Промет ослободен од ДДВ со право на одбивка на претходен данок',
    note: 'ДДВ не е пресметан согласно член 24 став 1 точка 1 од ЗДДВ',
    vatImpact: 'OSLOBODEN',
    taxGroupCode: 'DDV-G',
    common: true,
  },
  {
    code: 'DDV-8',
    categoryName: 'Промет ослободен од ДДВ со право на одбивка на претходен данок',
    note: 'ДДВ не е пресметан согласно член 24 став 1 од ЗДДВ',
    vatImpact: 'OSLOBODEN',
    taxGroupCode: 'DDV-G',
    common: true,
  },
  {
    code: 'DDV-9',
    categoryName: 'Промет ослободен од ДДВ без право на одбивка на претходен данок',
    note: 'ДДВ не е пресметан согласно член 23 од ЗДДВ',
    vatImpact: 'OSLOBODEN',
    taxGroupCode: 'DDV-G',
    common: true,
  },
  {
    code: 'DDV-A',
    categoryName: 'Стандардно оданочување со општа даночна стапка од 18%',
    note: '',
    vatImpact: 'STANDARD',
    taxGroupCode: 'DDV-A',
    common: true,
  },
  {
    code: 'DDV-B',
    categoryName: 'Стандардно оданочување со повластена даночна стапка од 5%',
    note: '',
    vatImpact: 'STANDARD',
    taxGroupCode: 'DDV-B',
    common: true,
  },
  {
    code: 'DDV-G',
    categoryName: 'Не е ДДВ обврзник',
    note: 'ДДВ не е пресметан согласно член 51 став 3 од ЗДДВ',
    vatImpact: 'NULA',
    taxGroupCode: 'DDV-G',
    common: true,
  },
  {
    code: 'DDV-V',
    categoryName: 'Стандардно оданочување со повластена даночна стапка од 10%',
    note: '',
    vatImpact: 'STANDARD',
    taxGroupCode: 'DDV-V',
    common: true,
  },
  {
    code: 'DDV-10-13-1-1',
    categoryName: 'Промет на добра кој не е предмет на оданочување во земјата согласно член 2 и 13 став 1 точка 1 од ЗДДВ',
    note: 'Прометот на добра не е предмет на оданочување во земјата согласно член 2 и 13 став 1 точка 1 од ЗДДВ',
    vatImpact: 'OSLOBODEN',
    taxGroupCode: 'DDV-G',
    common: false,
  },
  {
    code: 'DDV-10-13-1-2',
    categoryName: 'Промет на добра кој не е предмет на оданочување во земјата согласно член 2 и 13 став 1 точка 2 од ЗДДВ',
    note: 'Прометот на добра не е предмет на оданочување во земјата согласно член 2 и 13 став 1 точка 2 од ЗДДВ',
    vatImpact: 'OSLOBODEN',
    taxGroupCode: 'DDV-G',
    common: false,
  },
  {
    code: 'DDV-10-13-1-3',
    categoryName: 'Промет на добра кој не е предмет на оданочување во земјата согласно член 2 и 13 став 1 точка 3 од ЗДДВ',
    note: 'Прометот на добра не е предмет на оданочување во земјата согласно член 2 и 13 став 1 точка 3 од ЗДДВ',
    vatImpact: 'OSLOBODEN',
    taxGroupCode: 'DDV-G',
    common: false,
  },
  {
    code: 'DDV-10-13-1-5',
    categoryName: 'Промет на добра кој не е предмет на оданочување во земјата согласно член 2 и 13 став 1 точка 5 од ЗДДВ',
    note: 'Прометот на добра не е предмет на оданочување во земјата согласно член 2 и 13 став 1 точка 5 од ЗДДВ',
    vatImpact: 'OSLOBODEN',
    taxGroupCode: 'DDV-G',
    common: false,
  },
  {
    code: 'DDV-10-14-4-1',
    categoryName: 'Промет на услуги кој не е предмет на оданочување во земјата согласно член 2 и 14 став 4 точка 1 од ЗДДВ',
    note: 'Прометот не е предмет на оданочување во земјата согласно член 2 и 14 став 4 точка 1 од ЗДДВ',
    vatImpact: 'OSLOBODEN',
    taxGroupCode: 'DDV-G',
    common: false,
  },
  {
    code: 'DDV-10-14-4-10',
    categoryName: 'Промет на услуги кој не е предмет на оданочување во земјата согласно член 2 и 14 став 4 точка 10 од ЗДДВ',
    note: 'Прометот не е предмет на оданочување во земјата согласно член 2 и 14 став 4 точка 10 од ЗДДВ',
    vatImpact: 'OSLOBODEN',
    taxGroupCode: 'DDV-G',
    common: false,
  },
  {
    code: 'DDV-10-14-4-11',
    categoryName: 'Промет на услуги кој не е предмет на оданочување во земјата согласно член 2 и 14 став 4 точка 11 од ЗДДВ',
    note: 'Прометот не е предмет на оданочување во земјата согласно член 2 и 14 став 4 точка 11 од ЗДДВ',
    vatImpact: 'OSLOBODEN',
    taxGroupCode: 'DDV-G',
    common: false,
  },
  {
    code: 'DDV-10-14-4-2',
    categoryName: 'Промет на услуги кој не е предмет на оданочување во земјата согласно член 2 и 14 став 4 точка 2 од ЗДДВ',
    note: 'Прометот не е предмет на оданочување во земјата согласно член 2 и 14 став 4 точка 2 од ЗДДВ',
    vatImpact: 'OSLOBODEN',
    taxGroupCode: 'DDV-G',
    common: false,
  },
  {
    code: 'DDV-10-14-4-3',
    categoryName: 'Промет на услуги кој не е предмет на оданочување во земјата согласно член 2 и 14 став 4 точка 3 од ЗДДВ',
    note: 'Прометот не е предмет на оданочување во земјата согласно член 2 и 14 став 4 точка 3 од ЗДДВ',
    vatImpact: 'OSLOBODEN',
    taxGroupCode: 'DDV-G',
    common: false,
  },
  {
    code: 'DDV-10-14-4-4',
    categoryName: 'Промет на услуги кој не е предмет на оданочување во земјата согласно член 2 и 14 став 4 точка 4 од ЗДДВ',
    note: 'Прометот не е предмет на оданочување во земјата согласно член 2 и 14 став 4 точка 4 од ЗДДВ',
    vatImpact: 'OSLOBODEN',
    taxGroupCode: 'DDV-G',
    common: false,
  },
  {
    code: 'DDV-10-14-4-5',
    categoryName: 'Промет на услуги кој не е предмет на оданочување во земјата согласно член 2 и 14 став 4 точка 5 од ЗДДВ',
    note: 'Прометот не е предмет на оданочување во земјата согласно член 2 и 14 став 4 точка 5 од ЗДДВ',
    vatImpact: 'OSLOBODEN',
    taxGroupCode: 'DDV-G',
    common: false,
  },
  {
    code: 'DDV-10-14-4-6',
    categoryName: 'Промет на услуги кој не е предмет на оданочување во земјата согласно член 2 и 14 став 4 точка 6 од ЗДДВ',
    note: 'Прометот не е предмет на оданочување во земјата согласно член 2 и 14 став 4 точка 6 од ЗДДВ',
    vatImpact: 'OSLOBODEN',
    taxGroupCode: 'DDV-G',
    common: false,
  },
  {
    code: 'DDV-10-14-4-7',
    categoryName: 'Промет на услуги кој не е предмет на оданочување во земјата согласно член 2 и 14 став 4 точка 7 од ЗДДВ',
    note: 'Прометот не е предмет на оданочување во земјата согласно член 2 и 14 став 4 точка 7 од ЗДДВ',
    vatImpact: 'OSLOBODEN',
    taxGroupCode: 'DDV-G',
    common: false,
  },
  {
    code: 'DDV-10-14-4-8',
    categoryName: 'Промет на услуги кој не е предмет на оданочување во земјата согласно член 2 и 14 став 4 точка 8 од ЗДДВ',
    note: 'Прометот не е предмет на оданочување во земјата согласно член 2 и 14 став 4 точка 8 од ЗДДВ',
    vatImpact: 'OSLOBODEN',
    taxGroupCode: 'DDV-G',
    common: false,
  },
  {
    code: 'DDV-10-14-4-9',
    categoryName: 'Промет на услуги кој не е предмет на оданочување во земјата согласно член 2 и 14 став 4 точка 9 од ЗДДВ',
    note: 'Прометот не е предмет на оданочување во земјата согласно член 2 и 14 став 4 точка 9 од ЗДДВ',
    vatImpact: 'OSLOBODEN',
    taxGroupCode: 'DDV-G',
    common: false,
  },
  {
    code: 'DDV-10-BN',
    categoryName: 'Промет на добра и услуги во смисла на член 3 став 3 и член 6 став 6 од ЗДДВ по општа даночна стапка од 10%',
    note: '',
    vatImpact: 'STANDARD',
    taxGroupCode: 'DDV-V',
    common: false,
  },
  {
    code: 'DDV-11-A-G',
    categoryName: 'Промет на градежни услуги во земјата за кој данокот го пресметува примателот на прометот по општа даночна стапка од 18% (пренесување на даночна обврска согласно член 32-а став 1 точка 1 од ЗДДВ)',
    note: 'Пренесување на даночна обврска согласно член 32-а став 1 точка 1 од ЗДДВ',
    vatImpact: 'PRENESEN',
    taxGroupCode: 'DDV-A',
    common: false,
  },
  {
    code: 'DDV-11-A-О',
    categoryName: 'Промет на отпад во земјата за кој данокот го пресметува примателот на прометот по општа даночна стапка од 18% (пренесување на даночна обврска согласно член 32-а став 1 точка 2 од ЗДДВ)',
    note: 'Пренесување на даночна обврска согласно член 32-а став 1 точка 2 од ЗДДВ',
    vatImpact: 'PRENESEN',
    taxGroupCode: 'DDV-A',
    common: false,
  },
  {
    code: 'DDV-18-BN',
    categoryName: 'Промет на добра и услуги во смисла на член 3 став 3 и член 6 став 6 од ЗДДВ по општа даночна стапка од 18%',
    note: '',
    vatImpact: 'STANDARD',
    taxGroupCode: 'DDV-A',
    common: false,
  },
  {
    code: 'DDV-5-BN',
    categoryName: 'Промет на добра и услуги во смисла на член 3 став 3 и член 6 став 6 од ЗДДВ по општа даночна стапка од 5%',
    note: '',
    vatImpact: 'STANDARD',
    taxGroupCode: 'DDV-B',
    common: false,
  },
  {
    code: 'DDV-8-10',
    categoryName: 'Промет ослободен од ДДВ со право на одбивка на предходен данок согласно член 24 став 1 точка 10 од ЗДДВ',
    note: 'ДДВ не е пресметан согласно член 24 став 1 точка 10 од ЗДДВ',
    vatImpact: 'OSLOBODEN',
    taxGroupCode: 'DDV-G',
    common: false,
  },
  {
    code: 'DDV-8-2',
    categoryName: 'Промет ослободен од ДДВ со право на одбивка на предходен данок согласно член 24 став 1 точка 2 од ЗДДВ',
    note: 'ДДВ не е пресметан согласно член 24 став 1 точка 2 од ЗДДВ',
    vatImpact: 'OSLOBODEN',
    taxGroupCode: 'DDV-G',
    common: false,
  },
  {
    code: 'DDV-8-3',
    categoryName: 'Промет ослободен од ДДВ со право на одбивка на предходен данок согласно член 24 став 1 точка 3 од ЗДДВ',
    note: 'ДДВ не е пресметан согласно член 24 став 1 точка 3 од ЗДДВ',
    vatImpact: 'OSLOBODEN',
    taxGroupCode: 'DDV-G',
    common: false,
  },
  {
    code: 'DDV-8-4',
    categoryName: 'Промет ослободен од ДДВ со право на одбивка на предходен данок согласно член 24 став 1 точка 3 од ЗДДВ',
    note: 'ДДВ не е пресметан согласно член 24 став 1 точка 4 од ЗДДВ',
    vatImpact: 'OSLOBODEN',
    taxGroupCode: 'DDV-G',
    common: false,
  },
  {
    code: 'DDV-8-5',
    categoryName: 'Промет ослободен од ДДВ со право на одбивка на предходен данок согласно член 24 став 1 точка 5 од ЗДДВ',
    note: 'ДДВ не е пресметан согласно член 24 став 1 точка 5 од ЗДДВ',
    vatImpact: 'OSLOBODEN',
    taxGroupCode: 'DDV-G',
    common: false,
  },
  {
    code: 'DDV-8-6',
    categoryName: 'Промет ослободен од ДДВ со право на одбивка на предходен данок согласно член 24 став 1 точка 6 од ЗДДВ',
    note: 'ДДВ не е пресметан согласно член 24 став 1 точка 6 од ЗДДВ',
    vatImpact: 'OSLOBODEN',
    taxGroupCode: 'DDV-G',
    common: false,
  },
  {
    code: 'DDV-8-7',
    categoryName: 'Промет ослободен од ДДВ со право на одбивка на предходен данок согласно член 24 став 1 точка 7 од ЗДДВ',
    note: 'ДДВ не е пресметан согласно член 24 став 1 точка 7 од ЗДДВ',
    vatImpact: 'OSLOBODEN',
    taxGroupCode: 'DDV-G',
    common: false,
  },
  {
    code: 'DDV-8-8',
    categoryName: 'Промет ослободен од ДДВ со право на одбивка на предходен данок согласно член 24 став 1 точка 8 од ЗДДВ',
    note: 'ДДВ не е пресметан согласно член 24 став 1 точка 8 од ЗДДВ',
    vatImpact: 'OSLOBODEN',
    taxGroupCode: 'DDV-G',
    common: false,
  },
  {
    code: 'DDV-8-9',
    categoryName: 'Промет ослободен од ДДВ со право на одбивка на предходен данок согласно член 24 став 1 точка 9 од ЗДДВ',
    note: 'ДДВ не е пресметан согласно член 24 став 1 точка 9 од ЗДДВ',
    vatImpact: 'OSLOBODEN',
    taxGroupCode: 'DDV-G',
    common: false,
  },
  {
    code: 'DDV-8-DR',
    categoryName: 'Промет ослободен од ДДВ со право на одбивка на претходен данок врз основа на други прописи',
    note: 'ДДВ не е пресметан согласно друг пропис',
    vatImpact: 'OSLOBODEN',
    taxGroupCode: 'DDV-G',
    common: false,
  },
  {
    code: 'DDV-8-P',
    categoryName: 'Промет ослободен од ДДВ согласно член 24-а од ЗДДВ',
    note: 'ДДВ не е пресметан согласно член 24-а од ЗДДВ',
    vatImpact: 'OSLOBODEN',
    taxGroupCode: 'DDV-G',
    common: false,
  },
  {
    code: 'DDV-8-Z',
    categoryName: 'Промет со инвестициско злато',
    note: 'ДДВ не е пресметан согласно член 38-б од ЗДДВ',
    vatImpact: 'OSLOBODEN',
    taxGroupCode: 'DDV-G',
    common: false,
  },
  {
    code: 'DDV-8-ZDSJD',
    categoryName: 'Промет ослободен од ДДВ согласно член 15-б од Законот за донации и спонзорства во јавните дејности (ЗДСЈД)',
    note: 'ДДВ не е пресметан согласно член 15-б од ЗДСЈД',
    vatImpact: 'OSLOBODEN',
    taxGroupCode: 'DDV-G',
    common: false,
  },
  {
    code: 'DDV-9-1',
    categoryName: 'Промет ослободен од ДДВ без право на одбивка на предходен данок согласно член 23 точка 1 од ЗДДВ',
    note: 'ДДВ не е пресметан согласно член 23 точка 1 од ЗДДВ',
    vatImpact: 'OSLOBODEN',
    taxGroupCode: 'DDV-G',
    common: false,
  },
  {
    code: 'DDV-9-10',
    categoryName: 'Промет ослободен од ДДВ без право на одбивка на предходен данок согласно член 23 точка 10 од ЗДДВ',
    note: 'ДДВ не е пресметан согласно член 23 точка 10 од ЗДДВ',
    vatImpact: 'OSLOBODEN',
    taxGroupCode: 'DDV-G',
    common: false,
  },
  {
    code: 'DDV-9-11',
    categoryName: 'Промет ослободен од ДДВ без право на одбивка на предходен данок согласно член 23 точка 11 од ЗДДВ',
    note: 'ДДВ не е пресметан согласно член 23 точка 11 од ЗДДВ',
    vatImpact: 'OSLOBODEN',
    taxGroupCode: 'DDV-G',
    common: false,
  },
  {
    code: 'DDV-9-12',
    categoryName: 'Промет ослободен од ДДВ без право на одбивка на предходен данок согласно член 23 точка 12 од ЗДДВ',
    note: 'ДДВ не е пресметан согласно член 23 точка 12 од ЗДДВ',
    vatImpact: 'OSLOBODEN',
    taxGroupCode: 'DDV-G',
    common: false,
  },
  {
    code: 'DDV-9-13',
    categoryName: 'Промет ослободен од ДДВ без право на одбивка на предходен данок согласно член 23 точка 13 од ЗДДВ',
    note: 'ДДВ не е пресметан согласно член 23 точка 13 од ЗДДВ',
    vatImpact: 'OSLOBODEN',
    taxGroupCode: 'DDV-G',
    common: false,
  },
  {
    code: 'DDV-9-14',
    categoryName: 'Промет ослободен од ДДВ без право на одбивка на предходен данок согласно член 23 точка 14 од ЗДДВ',
    note: 'ДДВ не е пресметан согласно член 23 точка 14 од ЗДДВ',
    vatImpact: 'OSLOBODEN',
    taxGroupCode: 'DDV-G',
    common: false,
  },
  {
    code: 'DDV-9-15',
    categoryName: 'Промет ослободен од ДДВ без право на одбивка на предходен данок согласно член 23 точка 15 од ЗДДВ',
    note: 'ДДВ не е пресметан согласно член 23 точка 15 од ЗДДВ',
    vatImpact: 'OSLOBODEN',
    taxGroupCode: 'DDV-G',
    common: false,
  },
  {
    code: 'DDV-9-16',
    categoryName: 'Промет ослободен од ДДВ без право на одбивка на предходен данок согласно член 23 точка 16 од ЗДДВ',
    note: 'ДДВ не е пресметан согласно член 23 точка 16 од ЗДДВ',
    vatImpact: 'OSLOBODEN',
    taxGroupCode: 'DDV-G',
    common: false,
  },
  {
    code: 'DDV-9-17',
    categoryName: 'Промет ослободен од ДДВ без право на одбивка на предходен данок согласно член 23 точка 17 од ЗДДВ',
    note: 'ДДВ не е пресметан согласно член 23 точка 17 од ЗДДВ',
    vatImpact: 'OSLOBODEN',
    taxGroupCode: 'DDV-G',
    common: false,
  },
  {
    code: 'DDV-9-17-a',
    categoryName: 'Промет ослободен од ДДВ без право на одбивка на предходен данок согласно член 23 точка 17-a од ЗДДВ',
    note: 'ДДВ не е пресметан согласно член 23 точка 17-a од ЗДДВ',
    vatImpact: 'OSLOBODEN',
    taxGroupCode: 'DDV-G',
    common: false,
  },
  {
    code: 'DDV-9-17-b',
    categoryName: 'Промет ослободен од ДДВ без право на одбивка на предходен данок согласно член 23 точка 17-б од ЗДДВ',
    note: 'ДДВ не е пресметан согласно член 23 точка 17-б од ЗДДВ',
    vatImpact: 'OSLOBODEN',
    taxGroupCode: 'DDV-G',
    common: false,
  },
  {
    code: 'DDV-9-18',
    categoryName: 'Промет ослободен од ДДВ без право на одбивка на предходен данок согласно член 23 точка 18 од ЗДДВ',
    note: 'ДДВ не е пресметан согласно член 23 точка 18 од ЗДДВ',
    vatImpact: 'OSLOBODEN',
    taxGroupCode: 'DDV-G',
    common: false,
  },
  {
    code: 'DDV-9-19',
    categoryName: 'Промет ослободен од ДДВ без право на одбивка на предходен данок согласно член 23 точка 19 од ЗДДВ',
    note: 'ДДВ не е пресметан согласно член 23 точка 19 од ЗДДВ',
    vatImpact: 'OSLOBODEN',
    taxGroupCode: 'DDV-G',
    common: false,
  },
  {
    code: 'DDV-9-19-a',
    categoryName: 'Промет ослободен од ДДВ без право на одбивка на предходен данок согласно член 23 точка 19-а од ЗДДВ',
    note: 'ДДВ не е пресметан согласно член 23 точка 19-а од ЗДДВ',
    vatImpact: 'OSLOBODEN',
    taxGroupCode: 'DDV-G',
    common: false,
  },
  {
    code: 'DDV-9-19-b',
    categoryName: 'Промет ослободен од ДДВ без право на одбивка на предходен данок согласно член 23 точка 19-б од ЗДДВ',
    note: 'ДДВ не е пресметан согласно член 23 точка 19-б од ЗДДВ',
    vatImpact: 'OSLOBODEN',
    taxGroupCode: 'DDV-G',
    common: false,
  },
  {
    code: 'DDV-9-2',
    categoryName: 'Промет ослободен од ДДВ без право на одбивка на предходен данок согласно член 23 точка 2 од ЗДДВ',
    note: 'ДДВ не е пресметан согласно член 23 точка 2 од ЗДДВ',
    vatImpact: 'OSLOBODEN',
    taxGroupCode: 'DDV-G',
    common: false,
  },
  {
    code: 'DDV-9-20',
    categoryName: 'Промет ослободен од ДДВ без право на одбивка на предходен данок согласно член 23 точка 20 од ЗДДВ',
    note: 'ДДВ не е пресметан согласно член 23 точка 20 од ЗДДВ',
    vatImpact: 'OSLOBODEN',
    taxGroupCode: 'DDV-G',
    common: false,
  },
  {
    code: 'DDV-9-3',
    categoryName: 'Промет ослободен од ДДВ без право на одбивка на предходен данок согласно член 23 точка 3 од ЗДДВ',
    note: 'ДДВ не е пресметан согласно член 23 точка 3 од ЗДДВ',
    vatImpact: 'OSLOBODEN',
    taxGroupCode: 'DDV-G',
    common: false,
  },
  {
    code: 'DDV-9-4',
    categoryName: 'Промет ослободен од ДДВ без право на одбивка на предходен данок согласно член 23 точка 4 од ЗДДВ',
    note: 'ДДВ не е пресметан согласно член 23 точка 4 од ЗДДВ',
    vatImpact: 'OSLOBODEN',
    taxGroupCode: 'DDV-G',
    common: false,
  },
  {
    code: 'DDV-9-6',
    categoryName: 'Промет ослободен од ДДВ без право на одбивка на предходен данок согласно член 23 точка 6 од ЗДДВ',
    note: 'ДДВ не е пресметан согласно член 23 точка 6 од ЗДДВ',
    vatImpact: 'OSLOBODEN',
    taxGroupCode: 'DDV-G',
    common: false,
  },
  {
    code: 'DDV-9-7',
    categoryName: 'Промет ослободен од ДДВ без право на одбивка на предходен данок согласно член 23 точка 7 од ЗДДВ',
    note: 'ДДВ не е пресметан согласно член 23 точка 7 од ЗДДВ',
    vatImpact: 'OSLOBODEN',
    taxGroupCode: 'DDV-G',
    common: false,
  },
  {
    code: 'DDV-9-8',
    categoryName: 'Промет ослободен од ДДВ без право на одбивка на предходен данок согласно член 23 точка 8 од ЗДДВ',
    note: 'ДДВ не е пресметан согласно член 23 точка 8 од ЗДДВ',
    vatImpact: 'OSLOBODEN',
    taxGroupCode: 'DDV-G',
    common: false,
  },
  {
    code: 'DDV-9-8-a',
    categoryName: 'Промет ослободен од ДДВ без право на одбивка на предходен данок согласно член 23 точка 8-a од ЗДДВ',
    note: 'ДДВ не е пресметан согласно член 23 точка 8-a од ЗДДВ',
    vatImpact: 'OSLOBODEN',
    taxGroupCode: 'DDV-G',
    common: false,
  },
  {
    code: 'DDV-9-9',
    categoryName: 'Промет ослободен од ДДВ без право на одбивка на предходен данок согласно член 23 точка 9 од ЗДДВ',
    note: 'ДДВ не е пресметан согласно член 23 точка 9 од ЗДДВ',
    vatImpact: 'OSLOBODEN',
    taxGroupCode: 'DDV-G',
    common: false,
  },
  {
    code: 'DDV-9-DR',
    categoryName: 'Промет ослободен од ДДВ без право на одбивка на претходен данок врз основа на други прописи',
    note: 'ДДВ не е пресметан согласно друг пропис',
    vatImpact: 'OSLOBODEN',
    taxGroupCode: 'DDV-G',
    common: false,
  },
  {
    code: 'DDV-M-18',
    categoryName: 'Посебна шема за оданочување со општа даночна стапка согласно член 19 став 1 точка 4 од ЗДДВ',
    note: 'Маргинална шема за оданочување на употребувани добра',
    vatImpact: 'STANDARD',
    taxGroupCode: 'DDV-A',
    common: false,
  },
  {
    code: 'DDV-M-5',
    categoryName: 'Посебна шема за оданочување со повластена даночна стапка согласно член 19 став 1 точка 4 од ЗДДВ',
    note: 'Маргинална шема за оданочување на употребувани добра',
    vatImpact: 'STANDARD',
    taxGroupCode: 'DDV-B',
    common: false,
  },
  {
    code: 'DDV-M-ТО',
    categoryName: 'Посебна шема за оданочување на тур-оператори согласно член 38 од ЗДДВ',
    note: 'Маргинална шема за оданочување на тур-оператори',
    vatImpact: 'STANDARD',
    taxGroupCode: 'DDV-A',
    common: false,
  },
  {
    code: 'DDV-PNPI-B',
    categoryName: 'Промет извршен во рамки на постапка на присилна наплата согласно Законот за даночна постапка и во постапка за присилно извршување согласно со Законот за извршување, кој се оданочува со повластена даночна стапка од 5% согласно член 43-а од ЗДДВ',
    note: 'Промет во постапка на присилна наплата или присилно извршување согласно член 43-а од ЗДДВ',
    vatImpact: 'STANDARD',
    taxGroupCode: 'DDV-B',
    common: false,
  },
  {
    code: 'DDV-PNPI-DS-B',
    categoryName: 'Промет извршен во постапка на присилна наплата согласно Законот за даночна постапка и во постапка за присилно извршување согласно со Законот за извршување на кој се применува механизмот за пренесување на даночна обврска согласно член 32-а став 1 точка 3 од ЗДДВ',
    note: 'Пренесување на даночна обврска согласно член 32-а став 1 точка 3 од ЗДДВ',
    vatImpact: 'PRENESEN',
    taxGroupCode: 'DDV-B',
    common: false,
  },
  {
    code: 'DDV-PNPI-DS-V',
    categoryName: 'Промет извршен во постапка на присилна наплата согласно Законот за даночна постапка и во постапка за присилно извршување согласно со Законот за извршување на кој се применува механизмот за пренесување на даночна обврска согласно член 32-а став 1 точка 3 од ЗДДВ',
    note: 'Пренесување на даночна обврска согласно член 32-а став 1 точка 3 од ЗДДВ',
    vatImpact: 'PRENESEN',
    taxGroupCode: 'DDV-V',
    common: false,
  },
  {
    code: 'DDV-PNPI-DS-А',
    categoryName: 'Промет извршен во постапка на присилна наплата согласно Законот за даночна постапка и во постапка за присилно извршување согласно со Законот за извршување на кој се применува механизмот за пренесување на даночна обврска согласно член 32-а став 1 точка 3 од ЗДДВ',
    note: 'Пренесување на даночна обврска согласно член 32-а став 1 точка 3 од ЗДДВ',
    vatImpact: 'PRENESEN',
    taxGroupCode: 'DDV-A',
    common: false,
  },
  {
    code: 'DDV-PNPI-V',
    categoryName: 'Промет извршен во рамки на постапка на присилна наплата согласно Законот за даночна постапка и во постапка за присилно извршување согласно со Законот за извршување, кој се оданочува со повластена даночна стапка од 10% согласно член 43-а од ЗДДВ',
    note: 'Промет во постапка на присилна наплата или присилно извршување согласно член 43-а од ЗДДВ',
    vatImpact: 'STANDARD',
    taxGroupCode: 'DDV-V',
    common: false,
  },
  {
    code: 'DDV-PNPI-А',
    categoryName: 'Промет извршен во рамки на постапка на присилна наплата согласно Законот за даночна постапка и во постапка за присилно извршување согласно со Законот за извршување, кој се оданочува со општа даночна стапка од 18% согласно член 43-а од ЗДДВ',
    note: 'Промет во постапка на присилна наплата или присилно извршување согласно член 43-а од ЗДДВ',
    vatImpact: 'STANDARD',
    taxGroupCode: 'DDV-A',
    common: false,
  },
  {
    code: 'DDV-PS',
    categoryName: 'Проодни ставки',
    note: 'Проодна ставка согласно член 18 точка 3 од ЗДДВ',
    vatImpact: 'OSLOBODEN',
    taxGroupCode: 'DDV-G',
    common: false,
  },
  {
    code: 'DDV-uvoz',
    categoryName: 'ДДВ за увоз на добра',
    note: 'Данок кој се должи согласно член 32 точка 2 од ЗДДВ',
    vatImpact: 'PRENESEN',
    taxGroupCode: 'DDV-A',
    common: false,
  },
  {
    code: 'DDV-vaucer-E',
    categoryName: 'Еднонаменски вредносен ваучер согласно член 8-а и 8-б од ЗДДВ',
    note: 'Еднонаменски вредносен ваучер',
    vatImpact: 'STANDARD',
    taxGroupCode: 'DDV-A',
    common: false,
  },
  {
    code: 'DDV-vaucer-P',
    categoryName: 'Еднонаменски вредносен ваучер согласно член 8-а и 8-в од ЗДДВ',
    note: 'Повеќе наменски вредносен ваучер - Не се пресметува ДДВ',
    vatImpact: 'OSLOBODEN',
    taxGroupCode: 'DDV-G',
    common: false,
  },
];
